### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/textarea#4]
Component
States and mixins fix:
- [x] Remove all state colors from `Sass` and `Sass mixin` (active, focus, hover) and leave only `Normal` state
- [x] Enable `hover` state in `Sass mixin`
- [x] Enable `active` state in `Sass mixin`
- [x] Enable `focus` state in `Sass mixin`
- [x] Enable `disabled` state in `Sass mixin`
- [x] Enable `error` state in `Sass mixin`
- [x] Enable `valid` state in `Sass mixin`

**Comment by claudio-moya** [comment]
Theme
- [ ] Disabled state should not have any changes in active/hover
![disabled-hover](https://user-images.githubusercontent.com/10554673/74297001-dc971000-4d88-11ea-8e14-d29fc023ac7c.jpg)

- [ ] Change default inner border color feature of div background for `Error` and `Active` state.
Try: 

```css
.rex-textarea .rex-textarea-ui-border.error {
   backgroun-color: var(--rex-textarea-error-border-color, #DF0101);
...
}
```

Current:
![ui-border-now](https://user-images.githubusercontent.com/10554673/74297087-1e27bb00-4d89-11ea-83fc-b597305721d6.png)
How it should be:
![ui-border-fix](https://user-images.githubusercontent.com/10554673/74297088-1f58e800-4d89-11ea-9c8d-09af8877c1f0.png)
